package com.redsamurai.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 17 20:49:48 EEST 2016
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    String calculateEmployees(String firstName, String lastName);

    String login();
}

